"""xArm7 (7-DoF) no-gripper agent for pg3d reach.

ManiSkill bundles a ``xarm7_ability`` agent (xArm7 + Ability hand) but no bare
no-gripper xArm7, while the hardware target is a gripper-less xArm7. The bundled
``xarm7.urdf`` (PACKAGE_ASSET_DIR, no asset download) is the bare 7-DoF arm, so we
register a no-gripper agent over it, mirroring ManiSkill's own ``xarm6_nogripper``.

TCP is ``link_eef`` (the fixed flange link at the end of ``link7``); a ``tcp_pose``
property is added because — unlike Panda — ManiSkill's no-gripper agents only set
``self.tcp`` and the pg3d reach env reads ``agent.tcp_pose``.
"""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import numpy as np
import sapien.core as sapien
import torch
from mani_skill import PACKAGE_ASSET_DIR
from mani_skill.agents.base_agent import BaseAgent, Keyframe
from mani_skill.agents.controllers import *  # noqa: F401,F403 - controller configs + deepcopy_dict
from mani_skill.agents.controllers.passive_controller import PassiveControllerConfig
from mani_skill.agents.registration import register_agent
from mani_skill.utils import sapien_utils


# Combined xArm7 + Robotiq 2F-85 URDF, generated by
# dataset_generation/build_xarm7_robotiq_urdf.py (absolute mesh paths, so location
# is irrelevant to mesh resolution). Lives beside this module under assets/.
_XARM7_ROBOTIQ_URDF = str(Path(__file__).resolve().parent / "assets" / "xarm7_robotiq.urdf")


def _build_xarm7_gripper_colored_urdf() -> str:
    """Generate a colored xarm7_with_gripper URDF and return its absolute path.

    Copies the ManiSkill-bundled URDF into assets/ and injects URDF material color
    tags so that:
      - xarm_gripper_base_link → white  (the boxy housing)
      - all knuckle / finger links      → black
      - arm links (link_base … link7)   → unchanged (GLB meshes have baked colors)

    Mesh paths are kept as relative ``meshes/…`` references — mplib resolves them
    relative to the URDF directory, so a symlink ``assets/meshes → <venv>/xarm7/meshes``
    is created beside the output URDF. (mplib ignores absolute paths and prepends the
    URDF dir, causing double-path concatenation — symlinks+relative is required.)

    The file is written once; subsequent imports reuse the cached copy.
    """
    import os
    import xml.etree.ElementTree as ET

    xarm7_dir = Path(PACKAGE_ASSET_DIR) / "robots" / "xarm7"
    src = xarm7_dir / "xarm7_with_gripper.urdf"
    assets_dir = Path(__file__).resolve().parent / "assets"
    dst = assets_dir / "xarm7_with_gripper_colored.urdf"

    # Ensure the meshes symlink exists so relative paths in the URDF resolve for mplib.
    meshes_link = assets_dir / "meshes"
    if not meshes_link.exists() and not meshes_link.is_symlink():
        os.symlink(str(xarm7_dir / "meshes"), str(meshes_link))

    if dst.exists():
        return str(dst)

    tree = ET.parse(src)
    root = tree.getroot()

    # Color map: only gripper links get explicit material tags.
    # STL meshes carry no color; GLB arm meshes have baked-in colors → leave alone.
    _WHITE = "0.95 0.95 0.95 1.0"
    _BLACK = "0.12 0.12 0.12 1.0"
    color_map = {
        "xarm_gripper_base_link": _WHITE,
        "left_outer_knuckle":     _BLACK,
        "left_finger":            _BLACK,
        "left_inner_knuckle":     _BLACK,
        "right_outer_knuckle":    _BLACK,
        "right_finger":           _BLACK,
        "right_inner_knuckle":    _BLACK,
    }

    for link in root.iter("link"):
        rgba = color_map.get(link.get("name", ""))
        if rgba is None:
            continue
        mat_name = "white" if rgba == _WHITE else "black"
        for visual in link.findall("visual"):
            mat = ET.SubElement(visual, "material")
            mat.set("name", mat_name)
            color_elem = ET.SubElement(mat, "color")
            color_elem.set("rgba", rgba)

    dst.parent.mkdir(parents=True, exist_ok=True)
    tree.write(str(dst), xml_declaration=True, encoding="utf-8")
    return str(dst)


_XARM7_GRIPPER_COLORED_URDF = _build_xarm7_gripper_colored_urdf()


@register_agent()
class XArm7NoGripper(BaseAgent):
    uid = "xarm7_nogripper"
    urdf_path = f"{PACKAGE_ASSET_DIR}/robots/xarm7/xarm7.urdf"

    keyframes = dict(
        # A neutral "ready" pose: arm raised so the TCP sits in front of the base.
        rest=Keyframe(
            qpos=np.array([0.0, -0.4, 0.0, 0.5, 0.0, 0.9, 0.0]),
            pose=sapien.Pose([0, 0, 0]),
        ),
        zeros=Keyframe(
            qpos=np.zeros(7),
            pose=sapien.Pose([0, 0, 0]),
        ),
    )

    arm_joint_names = [
        "joint1",
        "joint2",
        "joint3",
        "joint4",
        "joint5",
        "joint6",
        "joint7",
    ]

    arm_stiffness = 1000
    arm_damping = [50, 50, 50, 50, 50, 50, 50]
    arm_friction = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    arm_force_limit = 100

    ee_link_name = "link_eef"

    def _after_init(self) -> None:
        self.tcp = sapien_utils.get_obj_by_name(self.robot.get_links(), self.ee_link_name)

    def is_static(self, threshold: float = 0.2):
        qvel = self.robot.get_qvel()  # 7 arm joints, no gripper
        return torch.max(torch.abs(qvel), 1)[0] <= threshold

    @property
    def tcp_pos(self):
        return self.tcp.pose.p

    @property
    def tcp_pose(self):
        return self.tcp.pose

    @property
    def _controller_configs(self):
        pd_joint_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=None,
            upper=None,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            friction=self.arm_friction,
            force_limit=self.arm_force_limit,
            normalize_action=False,
        )
        pd_joint_delta_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=-0.1,
            upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            use_delta=True,
        )
        pd_joint_target_delta_pos = deepcopy(pd_joint_delta_pos)
        pd_joint_target_delta_pos.use_target = True

        pd_ee_delta_pos = PDEEPosControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_ee_delta_pose = PDEEPoseControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            rot_lower=-0.1,
            rot_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_joint_target_delta_pose = deepcopy(pd_ee_delta_pose)
        pd_joint_target_delta_pose.use_target = True

        controller_configs = dict(
            pd_joint_pos=pd_joint_pos,
            pd_joint_delta_pos=pd_joint_delta_pos,
            pd_joint_target_delta_pos=pd_joint_target_delta_pos,
            pd_ee_delta_pos=pd_ee_delta_pos,
            pd_ee_delta_pose=pd_ee_delta_pose,
        )
        return deepcopy_dict(controller_configs)  # noqa: F405


@register_agent()
class XArm7Gripper(BaseAgent):
    """xArm7 (7-DoF) arm with the xArm parallel-jaw gripper attached.

    TCP is ``link_tcp`` — 172 mm above the gripper base, centered between the
    finger tips. The env's action space is 8-dim (7 arm joints + 1 gripper,
    ``drive_joint``, tracked via a :class:`PDJointPosMimicControllerConfig`, the
    other 5 gripper joints following it every control step at the ratio
    (``multiplier=1, offset=0``) the URDF's own ``<mimic joint="drive_joint">``
    tags declare). The DP3 training/state contract is arm-only (7-dim state,
    7-dim action, no gripper qpos at all -- see ``agent_pos_joint_indices``
    below) for this reach-only agent, since the gripper is held at a constant
    closed target the whole episode (see ``--gripper-open`` in
    write_xarm7_gripper_reach_dataset.py and ``gripper_open`` in
    policy_action_to_sim_action) and never needs the policy's attention here.
    A future pick-and-place variant that needs the policy to reason about or
    predict gripper state should override/remove ``agent_pos_joint_indices``
    (and set ``action_includes_gripper = True``) rather than reuse this one
    as-is -- this agent's dataset contract intentionally discards gripper qpos.

    Use this agent for reach tasks that need the gripper body present for
    sim-to-real point-cloud fidelity.
    """

    uid = "xarm7_gripper"
    # Arm-only agent_pos: this reach task never needs the policy to see gripper
    # qpos (it's held at a constant closed target throughout). Read by
    # maniskill_adapter.observation.adapt_observation via getattr(agent, ...),
    # so this applies uniformly to dataset generation and live rollout/eval.
    agent_pos_joint_indices = list(range(7))
    urdf_path = _XARM7_GRIPPER_COLORED_URDF

    # drive_joint is the sole actuated gripper DOF; the other 5 are followers that
    # mimic it 1:1 (see the URDF's own <mimic joint="drive_joint" .../> tags) --
    # the inner knuckles are the redundant broken-loop links and wander/jam if left
    # passive, so tying all five to drive_joint keeps the gripper a stable unit.
    gripper_joint_names = [
        "drive_joint",
        "left_finger_joint",
        "left_inner_knuckle_joint",
        "right_outer_knuckle_joint",
        "right_finger_joint",
        "right_inner_knuckle_joint",
    ]
    _gripper_mimic = {
        joint_name: {"joint": "drive_joint"}
        for joint_name in gripper_joint_names[1:]
    }
    # Gains match ManiSkill's own xarm6_robotiq mimic gripper exactly (stiffness=1e5,
    # damping=2000, force_limit=0.1) -- this codebase's closest precedent for a
    # mimic-driven xArm-family gripper. force_limit is the critical one: a 1e5-rad/s^2
    # spring with no meaningful force cap can deliver unbounded torque on any real
    # target change, which is what produced a qvel blowup (~100 rad/s) when this was
    # first tried at force_limit=50 (copied from the old *static*-hold config, which
    # never actually moved its target so a high cap was never exercised).
    gripper_stiffness = 1e5
    gripper_damping = 2000
    gripper_force_limit = 0.1
    gripper_friction = 1
    # rad; joint hard limit is [0, 0.85]. The action-space upper bound is backed off
    # the hard limit by _GRIPPER_LIMIT_MARGIN rather than 0.85 exactly: commanding
    # the drive target AT the hard stop makes the PD spring and the limit constraint
    # solver fight over the same boundary point, and tiny numerical perturbations
    # compound into a runaway joint-velocity blow-up (observed: gripper |qvel|
    # 0.2 -> 57 rad/s within 8 steps, bleeding a jerk into the arm). Backing off
    # leaves the valid target range strictly inside the joint limit so a "closed"
    # command never touches the constraint. Visually indistinguishable from fully
    # closed.
    _GRIPPER_LIMIT_MARGIN = 0.01
    _GRIPPER_CLOSED = 0.85 - _GRIPPER_LIMIT_MARGIN

    keyframes = dict(
        rest=Keyframe(
            # Gripper joints rest at the closed hold target so there is no reset
            # transient between keyframe qpos and the controller drive target.
            qpos=np.array([0.0, -0.4, 0.0, 0.5, 0.0, 0.9, 0.0,
                           *([_GRIPPER_CLOSED] * 6)]),
            pose=sapien.Pose([0, 0, 0]),
        ),
        zeros=Keyframe(
            qpos=np.zeros(13),
            pose=sapien.Pose([0, 0, 0]),
        ),
    )

    arm_joint_names = [
        "joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7",
    ]

    # Tuned for the gripper variant (vs. the no-gripper 1000/50 defaults). Replaying
    # planned curved paths with the closed-gripper mass on the flange, the baseline
    # 1000/50 PD drive lets the wrist (joint5, dragging joint6/7 via coupling) blow up
    # to 10-15 rad/s and overshoot the goal: at baseline every curved-path failure had
    # such a spike (245/246) and no success did (2/169). The added end-effector inertia
    # makes the baseline drive both too soft (stiffness) and, counter-intuitively, too
    # damped: higher damping fought the (smooth, plan-legal) motion into a worse spike,
    # while STIFFER + LESS damped tracks it cleanly. 5000/5 drove a 10-case battery of
    # known-failing curved seeds from 0/10 to 10/10 with peak |qvel| ~5.5 rad/s.
    # force_limit is provably irrelevant here (identical results 50 -> 20000) so it is
    # left at the no-gripper default.
    arm_stiffness = 5000
    arm_damping = [5, 5, 5, 5, 5, 5, 5]
    arm_friction = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    arm_force_limit = 100

    ee_link_name = "link_tcp"

    # Links that must not self-collide. The gripper is a broken four-bar loop, so at
    # the closed pose the inner/outer knuckles and fingers overlap and chatter against
    # each other (measured ~100 rad/s joint vibration + a 175-impulse link7↔base mount
    # contact that disturbs the arm). Giving them a shared group-2 bit makes them ignore
    # each other in the physics sim while STILL colliding with the environment; mplib
    # already handles self-collision during planning. Mirrors ManiSkill's xarm6_robotiq.
    _no_self_collision_links = [
        "link7", "link_eef", "xarm_gripper_base_link",
        "left_outer_knuckle", "left_inner_knuckle", "left_finger",
        "right_outer_knuckle", "right_inner_knuckle", "right_finger",
    ]

    def _after_init(self) -> None:
        self.tcp = sapien_utils.get_obj_by_name(self.robot.get_links(), self.ee_link_name)
        links_map = self.robot.links_map
        for link_name in self._no_self_collision_links:
            if link_name in links_map:
                links_map[link_name].set_collision_group_bit(group=2, bit_idx=31, bit=1)

    def is_static(self, threshold: float = 0.2):
        qvel = self.robot.get_qvel()[..., :7]  # arm joints only
        return torch.max(torch.abs(qvel), 1)[0] <= threshold

    @property
    def tcp_pos(self):
        return self.tcp.pose.p

    @property
    def tcp_pose(self):
        return self.tcp.pose

    @property
    def _controller_configs(self):
        pd_joint_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=None,
            upper=None,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            friction=self.arm_friction,
            force_limit=self.arm_force_limit,
            normalize_action=False,
        )
        pd_joint_delta_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=-0.1,
            upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            use_delta=True,
        )
        pd_joint_target_delta_pos = deepcopy(pd_joint_delta_pos)
        pd_joint_target_delta_pos.use_target = True

        pd_ee_delta_pos = PDEEPosControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_ee_delta_pose = PDEEPoseControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            rot_lower=-0.1,
            rot_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_joint_target_delta_pose = deepcopy(pd_ee_delta_pose)
        pd_joint_target_delta_pose.use_target = True

        # Single actionable gripper DOF (drive_joint); the other 5 joints mimic it
        # every control step via PDJointPosMimicController -- same mechanism as
        # Panda's panda_finger_joint1/2 mimic gripper, just 1 control : 5 mimic
        # instead of 1:1. This removes the closed-loop instability the same way the
        # old static hold did (all six driven together, never left passive-and-free)
        # while adding a real action dimension. upper is backed off the 0.85 hard
        # limit by _GRIPPER_LIMIT_MARGIN for the same reason the old static target
        # was (see class docstring / _GRIPPER_CLOSED comment above).
        gripper_pd_joint_pos = PDJointPosMimicControllerConfig(  # noqa: F405
            self.gripper_joint_names,
            lower=0.0,
            upper=self._GRIPPER_CLOSED,
            stiffness=self.gripper_stiffness,
            damping=self.gripper_damping,
            force_limit=self.gripper_force_limit,
            friction=self.gripper_friction,
            mimic=self._gripper_mimic,
        )

        controller_configs = dict(
            pd_joint_pos=dict(arm=pd_joint_pos, gripper=gripper_pd_joint_pos),
            pd_joint_delta_pos=dict(arm=pd_joint_delta_pos, gripper=gripper_pd_joint_pos),
            pd_joint_target_delta_pos=dict(
                arm=pd_joint_target_delta_pos, gripper=gripper_pd_joint_pos
            ),
            pd_ee_delta_pos=dict(arm=pd_ee_delta_pos, gripper=gripper_pd_joint_pos),
            pd_ee_delta_pose=dict(arm=pd_ee_delta_pose, gripper=gripper_pd_joint_pos),
        )
        return deepcopy_dict(controller_configs)  # noqa: F405


@register_agent()
class XArm7Robotiq(BaseAgent):
    """xArm7 (7-DoF) arm with the Robotiq 2F-85 parallel-jaw gripper attached.

    The 2F-85 subtree is grafted onto xArm7's ``link_eef`` flange (see
    dataset_generation/build_xarm7_robotiq_urdf.py). TCP is the Robotiq ``eef``
    link — 150 mm past the flange, centered between the finger pads.

    Mirrors :class:`XArm7Gripper`'s reach contract: action space is 7-dim (arm
    joints only); the gripper joints are passive and rest at qpos=0 = fully open.
    Unlike the xArm gripper, the Robotiq fingers are an underactuated four-bar
    linkage, so the inner-finger/inner-knuckle loop closure is restored with two
    SAPIEN drives in :meth:`_after_loading_articulation` (lifted from
    ManiSkill's ``XArm6Robotiq``), and the dense gripper self-collisions are
    disabled via collision-group bits there too. The watertight Robotiq collision
    meshes load cleanly in mplib — the reason for switching off the xArm gripper.
    """

    uid = "xarm7_robotiq"
    urdf_path = _XARM7_ROBOTIQ_URDF

    # Friction material + contact pads so the gripper can actually hold things if
    # a future task closes it (harmless for reach).
    urdf_config = dict(
        _materials=dict(
            gripper=dict(static_friction=2.0, dynamic_friction=2.0, restitution=0.0)
        ),
        link=dict(
            left_inner_finger_pad=dict(material="gripper", patch_radius=0.1, min_patch_radius=0.1),
            right_inner_finger_pad=dict(material="gripper", patch_radius=0.1, min_patch_radius=0.1),
        ),
    )

    # The 6 revolute gripper joints (held passively open for reach).
    _gripper_passive_joint_names = [
        "left_outer_knuckle_joint",
        "left_inner_knuckle_joint",
        "left_inner_finger_joint",
        "right_outer_knuckle_joint",
        "right_inner_knuckle_joint",
        "right_inner_finger_joint",
    ]

    keyframes = dict(
        rest=Keyframe(
            qpos=np.array([0.0, -0.4, 0.0, 0.5, 0.0, 0.9, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
            pose=sapien.Pose([0, 0, 0]),
        ),
        zeros=Keyframe(
            qpos=np.zeros(13),
            pose=sapien.Pose([0, 0, 0]),
        ),
    )

    arm_joint_names = [
        "joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7",
    ]

    arm_stiffness = 1000
    arm_damping = [50, 50, 50, 50, 50, 50, 50]
    arm_friction = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    arm_force_limit = 100

    ee_link_name = "eef"

    def _after_loading_articulation(self) -> None:
        # Restore the Robotiq four-bar loop closure: drive each inner_finger_pad to
        # its inner_knuckle. Poses precomputed by ManiSkill (XArm6Robotiq); identical
        # gripper geometry, so they transfer unchanged.
        p_f_right = [-1.6048949e-08, 3.7600022e-02, 4.3000020e-02]
        p_p_right = [1.3578170e-09, -1.7901104e-02, 6.5159947e-03]
        p_f_left = [-1.8080145e-08, 3.7600014e-02, 4.2999994e-02]
        p_p_left = [-1.4041154e-08, -1.7901093e-02, 6.5159872e-03]

        outer = self.robot.active_joints_map["right_inner_finger_joint"]
        knuckle = self.robot.active_joints_map["right_inner_knuckle_joint"]
        right_drive = self.scene.create_drive(
            knuckle.get_child_link(), sapien.Pose(p_f_right),
            outer.get_child_link(), sapien.Pose(p_p_right),
        )
        right_drive.set_limit_x(0, 0)
        right_drive.set_limit_y(0, 0)
        right_drive.set_limit_z(0, 0)

        outer = self.robot.active_joints_map["left_inner_finger_joint"]
        knuckle = self.robot.active_joints_map["left_inner_knuckle_joint"]
        left_drive = self.scene.create_drive(
            knuckle.get_child_link(), sapien.Pose(p_f_left),
            outer.get_child_link(), sapien.Pose(p_p_left),
        )
        left_drive.set_limit_x(0, 0)
        left_drive.set_limit_y(0, 0)
        left_drive.set_limit_z(0, 0)

        # Disable the dense gripper-internal (and gripper<->flange) collisions in sim;
        # the SRDF handles the same set for mplib planning.
        gripper_links = [
            "right_inner_knuckle", "right_outer_knuckle", "left_inner_knuckle",
            "left_outer_knuckle", "right_inner_finger_pad", "left_inner_finger_pad",
            "right_outer_finger", "left_outer_finger", "robotiq_arg2f_base_link",
            "right_inner_finger", "left_inner_finger",
            "link_eef",  # flange the gripper bolts to
        ]
        for link_name in gripper_links:
            self.robot.links_map[link_name].set_collision_group_bit(group=2, bit_idx=31, bit=1)

    def _after_init(self) -> None:
        self.finger1_link = sapien_utils.get_obj_by_name(
            self.robot.get_links(), "left_inner_finger_pad"
        )
        self.finger2_link = sapien_utils.get_obj_by_name(
            self.robot.get_links(), "right_inner_finger_pad"
        )
        self.tcp = sapien_utils.get_obj_by_name(self.robot.get_links(), self.ee_link_name)

    def is_static(self, threshold: float = 0.2):
        qvel = self.robot.get_qvel()[..., :7]  # arm joints only
        return torch.max(torch.abs(qvel), 1)[0] <= threshold

    @property
    def tcp_pos(self):
        return self.tcp.pose.p

    @property
    def tcp_pose(self):
        return self.tcp.pose

    @property
    def _controller_configs(self):
        pd_joint_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=None,
            upper=None,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            friction=self.arm_friction,
            force_limit=self.arm_force_limit,
            normalize_action=False,
        )
        pd_joint_delta_pos = PDJointPosControllerConfig(  # noqa: F405
            self.arm_joint_names,
            lower=-0.1,
            upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            use_delta=True,
        )
        pd_joint_target_delta_pos = deepcopy(pd_joint_delta_pos)
        pd_joint_target_delta_pos.use_target = True

        pd_ee_delta_pos = PDEEPosControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_ee_delta_pose = PDEEPoseControllerConfig(  # noqa: F405
            joint_names=self.arm_joint_names,
            pos_lower=-0.1,
            pos_upper=0.1,
            rot_lower=-0.1,
            rot_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            friction=self.arm_friction,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,
        )
        pd_joint_target_delta_pose = deepcopy(pd_ee_delta_pose)
        pd_joint_target_delta_pose.use_target = True

        # All 6 gripper joints passive: light damping holds them open at qpos=0.
        gripper_passive = PassiveControllerConfig(  # noqa: F405
            joint_names=self._gripper_passive_joint_names,
            damping=10,
            friction=1,
        )

        controller_configs = dict(
            pd_joint_pos=dict(arm=pd_joint_pos, gripper=gripper_passive),
            pd_joint_delta_pos=dict(arm=pd_joint_delta_pos, gripper=gripper_passive),
            pd_joint_target_delta_pos=dict(arm=pd_joint_target_delta_pos, gripper=gripper_passive),
            pd_ee_delta_pos=dict(arm=pd_ee_delta_pos, gripper=gripper_passive),
            pd_ee_delta_pose=dict(arm=pd_ee_delta_pose, gripper=gripper_passive),
        )
        return deepcopy_dict(controller_configs)  # noqa: F405
